### PR TITLE
replaced run.bat with cli.js closes #9

### LINKED ISSUE #9: npm\atom-shell.cmd not working
This probably isn't really an issue with this project but npm on windows 8.1. But I think I have a better chance of resolving this with somebody who hasn't got 800 issues on there hands. I hope you don't mind, otherwise feel free to close this issue straight away.

On windows 8.1 in the folder ~\AppData\Roaming\npm there lie all the `.cmd` scripts to launch global executable npm packages including atom-shell.

This is the content for the atom-shell `.cmd` file:
```shell
@IF EXIST "%~dp0\/bin/bash.exe" (
  "%~dp0\/bin/bash.exe"  "%~dp0\node_modules\atom-shell\run.bat" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  /bin/bash  "%~dp0\node_modules\atom-shell\run.bat" %*
)
```

Windows will arrive at the last line in this script:

```shell
/bin/bash  "%~dp0\node_modules\atom-shell\run.bat" %*
```
and then fail, because there is no such thing as /bin/bash on windows?!?!?!

### PR DESCRIPTION
**Pull request by JamesKyburz**

### CODE REVIEW

**Comment by JamesKyburz** [comment]
This fixes installs on windows using both cmd.exe or git bash. And still works in a normal environment ;)

The problem was that the cmd-shim was run using the shebang in the initial run.bat file, not the one written to by install.js. Adding a preinstall step fixes this.

I couldn't find a better way to detect the presence of a git bash environment in windows other than checking process.env.TERM. It works but if anyone knows of a better way let us know!

FYI My first attempt was to wrap everything in a cli.js file and spawn using the path. Getting rid of run.bat, However this worked in all environments except you guessed it..our friend windows.

**Comment by JamesKyburz** [comment]
Any thoughts on this?

FYI The windows fix for [this dll missing issue](https://github.com/atom/electron/issues/1442) has now been released.

**Comment by jugglingnutcase** [comment]
i think that writing the `run.bat` file doesn't need to be split over two different scripts (one to write and then another to later append), it could all be done in the preinstall script. i think that might make it more clear what's going on for future contributors.

**Comment by JamesKyburz** [comment]
@jugglingnutcase I don't think it's possible because the packages in `package.json` aren't available in the preinstall step.

There might we a way but that's why I split it up.

**Comment by JamesKyburz** [comment]
I removed the preinstall step and run.bat using cli.js instead.

The original issue with spawn in windows was due do the missing dll's

I have tested this on yosemite, ubuntu 14.04, windows cmd.exe and git bash

**Comment by dotnetmentor** [comment]
@maxogden @mafintosh thoughts on this?

**Comment by JamesKyburz** [comment]
@maxogden @mafintosh It was me asking your thoughts on this. Multiple github accounts on multiple devices late at night.....

**Comment by maxogden** [comment]
we were on a trip this week, sheesh. hold your horses :) will try to review soon

**Comment by JamesKyburz** [comment]
:)

**Comment by mafintosh** [comment]
@maxogden the symlink approach i was talking about won't work in windows if npm uses the cmd-shim before running the install script (what @JamesKyburz is describing [here](https://github.com/mafintosh/electron-prebuilt/pull/13#issuecomment-95141818))

**Comment by mafintosh** [comment]
@JamesKyburz thanks!

**Comment by mafintosh** [comment]
Released in 0.25.1-1

**Comment by JamesKyburz** [comment]
Great thx!

**Pull request merged**
