### PR TITLE
Added update script closing #16

### PR DESCRIPTION
**Pull request by JamesKyburz**
Bash script updating version.

### CODE REVIEW

**Comment by maxogden** [comment]
this looks good, im just too busy to test + review at the moment, sorry! other maintainers: feel free

**Comment by ingorichter** [comment]
does anybody have time to review this? Would be great to get this merged.

**Comment by maxogden** [comment]
BTW yesterday we started using this server to handle npm publishing whenever atom/electron does a new GitHub Release https://github.com/johnmuhl/electron-prebuilt-updater/blob/master/index.js

Is this PR still necessary given the functionality of electron-prebuilt-updater?

**Comment by JamesKyburz** [comment]
Cool!! Now that updating install.js isn't needed (because it now uses package.json - which is way better) I think my PR isn't needed.

**Comment by maxogden** [comment]
@JamesKyburz thanks for the PR anyway, it got the ball rolling!

**Comment by JamesKyburz** [comment]
@maxogden thx! glad you got it automated!

**Pull request closed without merging**
