### PR TITLE
API returns electron version

### PR DESCRIPTION
**Pull request by szwacz**
In my case I'd like to have it because it simplifies integration with https://github.com/electronjs/electron-rebuild

**But**, to make this possible I had to break the API. As you know current `require('electron')` returns just one string and string as a primitive value can't be extended with additional fields.
So I won't be angry if this PR will be dismissed, (well maybe a little, because decission made in the past to just return one string as `module.exports` was let's say disputable ;)

### CODE REVIEW

**Comment by szwacz** [comment]
Would like to know if you at least take into consideration merging it :)

**Comment by maxogden** [comment]
Oops sorry, have been busy lately. I would say a breaking change wouldn't be worth the hassle, but I would be okay with a separate entrypoint e.g. `require('electron-prebuilt/version')`

**Comment by maxogden** [comment]
actually just realized, does `require('electron-prebuilt/package.json')` already do what you want?

**Comment by szwacz** [comment]
Hmm, `require('electron-prebuilt/package.json')` isn't the neatest solution but does the job. Thanks for this hack.

**Pull request closed without merging**
